### ISSUE TITLE
Can not sign app; got rejected

### ISSUE THREAD

**Issue by broderix** [alexeyst/node-webkit-macappstore#2]
I have tried to sign this app like this
$ codesign --force -d --deep-verify -v -v -v -s "MYIDENTITY" node-webkit.app
and verify it like that
$ spctl -a -t exec -vv node-webkit.app
node-webkit.app: rejected
origin=3rd Party Mac Developer Application: COMPANY INC (MYIDENTITY)

I also tried https://github.com/trevorlinton/chromium/blob/node/macstore_sign.sh tool by @trevorlinton, but got the same result

OSX 10.10.2 and xcode Version 6.1.1 (6A2008a) (also tried xcode 6.2)

**Comment by alexeyst** [comment]
Hey @broderix 

That's fine. The app says "rejected" because it hasn't been downloaded from the AppStore and doesn't contain MAS receipt. It, however, won't stop it from being approved by AppStore. So if you can run your app in the sandboxed mode, it's fine. See some detailed information about this here: https://github.com/nwjs/nw.js/issues/3258

**Comment by alexeyst** [comment]
Closing this as resolved.
